version: '3.8'

services:

  eshop:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: delight123
      MYSQL_DATABASE: ecommerce-on-cloud
      
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis-cart:
    image: redis:latest
    container_name: cart
    ports:
      - 6379:6379
    command: ["redis-server","--appendonly", "yes"]

    volumes:
      - redis-data:/data
     
   

volumes:
  redis-data:
  mysql-data:
 

